= What I like about Japan

Being in Japan for already 40 days, I noticed a lot of stuff that makes my life pleasant. I'll try to give a summary of some of the positive things I encountered so far. First, I also wanted to summarize the stuff I don't like about Japan so far (and yes, there are some points you won't like about any country), but I'll keep that for another post, so stay tuned!

== Public transport

Most of you know the legends and fairy tales about perfect train systems on which the train never comes late: the tales are true, my friend! This is absolutely the greatest thing I have encountered so far. Being used to public transport in Belgium, especially busses, Japanese public transport is a relief! Trains arrive and leave ON TIME, and then I mean SPOT-ON! In Belgium, you have to be happy if your train only arrives 5 minutes late, which is still considered on time by the NMBS (the Belgian rail company).

I commute between the stations Musashi-Kosugi (near my apartment) and Shibuya (near to my school) and can choose between 3 different kinds of trains on my line: Local, Express and Commuter Express. Local trains stop at every station on the line and hence are the slowest ones. Shibuya is the first station on the line and Musashi-Kosugi the eleventh, so 10 stops until I reach my destination, which takes about half an hour. The Express train skips 3 to 4 stations, but the fastest trains on the line are the Commuter Express trains. These only stop at the greater stations where you can transfer to another line. Now of course, everyone is keen on commuting quicker, which means that a lot of people prefer the Commuter Express, especially in the morning when people have to get to work or school in time. Result: whenever I tried to take the Commuter Express in the mornings, I was literally being a sardine in a can. (Could I get some lemon and salt with that?) So I prefer taking the local train instead, which will also be crowded in the mornings, but at least you can move your arms to catch your phone and read a newspaper. Commuting time doesn't differ that much after all in my case. I guess I can gain only 10 minutes in the morning and since I leave pretty early to school, it doesn't really matter to me. However, in the early afternoon (let's say 15:00) the Commuter Express really gives a benefit. Then, it only takes me 10 to 12 minutes to commute between my stations and you can sit comfortably too since there isn't that much crowd.

Next to this, there are general habits in train stations that make life easier and bearable for everyone: queueing. *_What do you mean? People actually properly stand in lines to enter the train? Can people actually behave civilized?_* EXACTLY, no fighting to get in or out of the train, people properly wait until it is their turn to get in. And not only for entering the train! In huge stations, like Shibuya, you have thousands of people transferring and commuting. Therefore, a dozen of train lines enter this station, making it a huge maze, with several floors. Having so much floors in your station means you definitely have to use escalators to get around. In Japan, there is the nice habit to keep one half of the escalator free for people who are in a hurry and therefore want to walk/run on the escalators. Of course, before you get on the escalator, you queue properly in the correct line: the line for people that run on the escalators, or the line for people that stand still on the escalator.

And then finally the last but certainly not the least thing I like about Japanese public transport: navigation. Having huge stations means you can easily get lost. However, the signs come to a help. The stations are overwhelmed with them. And luckily: all these signs have English translations! As a foreigner this is really a relief.  You simply follow the arrows to the line or exit you want to reach and done.

== General kindness

Whenever you enter a store, you will be greeted by most of the staff. Their smiles and bows bring you in a really happy mood. But this kindness is not only present in stores, in the stations you have the common habit not to bother each other on the trains and queue properly for escalators and entering the train wagon. Japan has a huge population, especially in Tokyo, so you have to cope with the fact that there are a lot of people around you. When you want to feel at ease, you should ensure that you let others feel at ease. The best way to deal with each other is being calm and polite. But of course, this has to come from both sides! Don't be rude, nor stare at people! Offer your seat for the elderly! Don't, but really, DON'T play music aloud on the train! There are headsets, so use them! Turn the ringtone of your mobile phone out.

People also help you whenever you ask them to! Let me give you an anecdote to illustrate this: last week, I was at a おこのみやき (okonomiyaki) restaurant with the other Fujitsu boys and wanted to order a new dish that we hadn't tried before: もんじゃやき (monjayaki). Normally, you grill/cook the dish yourself at your table, but we had no clue how to do this properly since it wasn't exactly the same as the okonomiyaki we were used to. So we asked the waiter how to do this and he grilled it for us! He really took effort in showing it to us instead of just explaining it briefly, which I really appreciate.

== Public bathrooms are free AND CLEAN

In Belgium, you easily pay 50 cents of 'maintenance fee' to use a public toilet and from time to time these bathrooms have a rather 'used' impression. But people in Japan have a better understanding of general hygiene in my opinion and leave the toilets behind in the way they want to encounter them: clean. So no need to pay a toilet lady that has to supervise the bathroom continuously and clean the place. Of course these toilets get properly cleaned, but at least in Japan the staff does not have to be present all the time to check whether you aim correctly or not.

== Convenience stores, convenience stores everywhere

コンビニ (konbini, short for convenience store) are everywhere. For the Belgian reader, you can compare these shops to Carrefour Express or City Delhaize. Just across my apartment, there is a 7-Eleven, where I can buy warm bento's whenever I don't want to go out for dinner (At the moment I don't cook myself but I'm planning to!). Next to this, these stores are 24/7 open! How べんり　(benri: convenient) is that? The prices are bit more expensive than in the supermarket, but people gladly pay a bit more for the convenience. Next to buying food, I can also withdraw cash from the ATM over there.

== Food establishments at fair prices

There's no need to cook for yourself if you don't want to. There are tons of places you can go to have lunch or dinner. Going out for food is quite common here, and therefore it doesn't have to be expensive at all! You'd guess of course you can only get junk food at low prices but less is true. You have a lot of simple dishes that can be bought that aren't that fat. The greatest example might be ラーメン (raamen: noodle soup) which is cheap and you feel satisfied and full after one bowl. As a person that has always struggled with his weight, I can say that I managed to keep my weight stable until now!

== 百円ストアー

In Europe we have a similar thing, a 1 euro store, but what you often find in such stores is mostly rubbish. However in a 百円ストアー (hyaku-en stoa, 100 yen store) you find a lot of simple necessities that make your daily life easier: chopsticks, cups, glasses, plates, knifes, paper, pencils... you find a lot of stuff at very low prices. Most of the stuff costs 100 yen (which is currently around 86 eurocents if I recall correctly), but whenever it is more expensive, it is notified on the product. However, don't forget you pay 8% of taxes on your products, so you actually pay 108 yen for the product if it's labeled to be 100 yen!

== Crazy food combinations

Ever considered eating chips with honey? Or what did you think of mayonnaise on your omelet? Ketchup on your rice?! For me, it sounded really strange and disgusting, but I was wrong. Being in a new country means you will get to know new types of food and habits that you're not used to, which is why I was really surprised by some food combinations they make in Japan, but certainly in a positive way. It's really good! Ever considered pouring warm egg yolk (the yellow part of an egg) over your rice? You should give it a try! 

== Supermarkets are open until 22:00

That's quite late in comparison to Belgium, where the supermarkets close at 20:00 (except for 21:00 on Fridays). And you know what's even better? The hour before they close, they give discounts to all the fresh food that's still available and otherwise has to be thrown away! Also the supermarkets are open on every day. Even on Sundays! I weekly visit the supermarket before closing time to buy some milk, cereal and some other drinks in big bottles. But I also check whether there is a bento or some other dish that I can take along as late night dinner at 50% of the price.

Guess I'll stop this post for now. Next time, I'll try to introduce my school life in Shibuya. Hope you still enjoy my blog! Stay tuned!
