= Why I left

After being already 10 days in Japan, I finally have found the opportunity to write my first post. We will start at the beginning, which is the reason why I left to Japan. Most of you know this already, but for the people that don't, I'll try to give a quick summary.

During my first year of my Master's program, I was already thinking about what I could do afterwards. Normally, one starts looking for a job or continues his/her studies with an additional Master's program or PhD. I chose I could go for a PhD, since I would love to perform research in my further career and getting a PhD is in my opinion the right way to get into R&D later on. However, having not that much practical experience in Computer Science, I wanted to gain some before starting a career.  That's why I was planning to do an intern- or traineeship somewhere during summer.

As most of you know, I am also a big fan of Japan. I love watching anime, but besides the wacko entertainment the Japanese provide, I also appreciate their ancient culture. I practice Jiu-Jitsu and I'd love to learn Kendo one day. I admire their spirit for perfectionism and their attitude to put collective harmony above personal benefit. Japan has been a source of inspiration since my childhood. That's why I always was looking forward to visit the country one day. 

Around November 2014, I received an e-mail from my faculty. It was forwarded publicity from our university's International Relationships Office. I quickly skimmed the email and noticed it told about an international exchange program, Vulcanus, for scientists and engineers. You would get the opportunity to work in the research department of a multinational. This sounded very interesting, since I wanted to do an internship and on top of that, it concerned research. However, the fact that the internship would be international scared me a bit. Nevertheless, I read the email a second time, a bit more thoroughly and that's when it happened. I discovered you would get a 4-month language course and afterwards start your 8-month traineeship in... Japan.

A whole year in the land of my dreams, gaining some practical experience in a research department and learn Japanese as a surplus. This email came like some revelation at that moment.  It combined all the topics that I was wondering about around that period. I decided to apply for this exchange program in my graduation year. This program lasts a whole year, which is why I wanted to finish my studies first. After filling in some forms, writing a CV and motivation letter, gathering documents from my university and an acknowledgement from my doctor that I'm in a proper condition to travel abroad, I had put everything together to apply for the http://www.eu-japan.eu/events/vulcanus-japan[Vulcanus in Japan] program, although without that much hope to succeed. It is an exchange program on European level, so I was convinced I wouldn't be able to compete with the other applicants during the selection procedures. However, in January 2016 I got the verdict: I was selected to go to Japan. The committee that had selected me, recommended a particular traineeship at http://www.fujitsu.com/jp/group/labs/en/[Fujitsu Laboratories]. I had to write a motivation letter to the company and if I happened to be chosen by the company, I was ready to go.

As you all know by now, Fujitsu Laboratories selected me for one of their internships and I am currently residing in Nakahara, Kawasaki City, in the Kanagawa prefecture, just outside of Tokyo. From September to December, I will daily commute to Shibuya, Tokyo to study Japanese at http://www.naganuma-school.ac.jp/[The Naganuma School, Tokyo School of Japanese Language], together with the other 33 Vulcanus trainees. In my next post, I will talk more in detail about my flight and my first days in Japan. 
