= Kamakura 

Now that I have told about most of the formal stuff that I'm dealing with in Japan, let's tell a bit about the places I have visited so far. I have visited several parks in  Tokyo, made a stop at the Pokémon Center in Ikebukoro and wandered around in Akihabara drooling on all the anime merchandise I saw over there, but I still need to explore a lot of Tokyo Last month I visited the beatiful city Kamakura (鎌倉) with 3 other Vulcanus trainees. The city is only 50 kilometers from Tokyo and has a long history, which makes it an attractive spot for tourist.
What can you expect to find in Kamakura? Well it's very simply: religious areas, tons and tons of them. The city is surrounded by Shinto shrines (神社：じんじゃ; jinja) and Buddhist temples (お寺：おてら; otera)

I'm not going to waste a lot of words and let the pictures speak for themselves: https://goo.gl/photos/G2qetVywN4awRXzq5[*ALBUM*]
++++
<style>
    .google-maps {
        position: relative;
        padding-bottom: 75%; // This is the aspect ratio
        height: 0;
        overflow: hidden;
    }
    .google-maps iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100% !important;
        height: 100% !important;
    }
</style>
 
<div class="google-maps">
<iframe src="https://www.google.com/maps/d/embed?mid=1ich19Hjatxr5G3xoG0cAjqbUIn0" width="640" height="480" frameborder="0" style="border:0"></iframe>
</div>
++++