= November Update

It has been a whole month since I made my last post.
Time just keeps flying...
The final weeks at Naganuma School have started.
All of a sudden, I start to realize that the end of a hard, tough, but yet oh so fulfilling period in my lifetime is nearing.
Next week, I will have my final presentation, my graduation ceremony from Naganuma School.
I'll have to prove to the outside world what 3 months of cramming words, verbs and grammar into your head can result in.
But I don't have to do it alone, the presentations are done in groups of 2 people.
I was coupled to my buddy, Shaikh, from the Netherlands.
We are currently finishing our script and I can say to feel satisfied about the result.

What actually began as a blog post about an afternoon spent listening to two great bands, turned out into a compilation of what I have experienced through November since I haven't written anything here for a while.
And since I had a rare free evening in the middle of a school week, I realised I could finally start to spit my gut properly.
So be prepared for a rather long story.
Grab you popcorn, fetch some coke, sit down and here we go!

Let me start by saying this: school was rather tough for me in November.
I think I started to get tired of continuously stuffing my head with new content every night.
From the moment I wake up, until the last second I fall asleep, my mind is trying to process new, freshly learnt Japanese.
We have come to a point that the number of words and verbs we have encountered are that numereous, you cannot use them anymore on a regular basis.
Result: you start to forget, you start to forget a lot!
The only manner to regain forgotten knowledge: review it.
The thing is, I don't find the motivation to do this properly, since I already cram those daily 30 new words in my head and these words are at that point in time more important to me than the previous 628 (to give it a random number).
But I have let the frustration behind me and took peace with the fact that my brain cannot simply remember words that I only have encountered once on a piece of paper and never properly used in my daily life ever since.
I am sure I will find some time and motivation in the future to properly review those once I have had my break during the Holidays.
To strengthen this statement: I bought a vocabulary book to study for my second JLPT attempt in July 2017.

Now that I have mentioned JLPT, allow me to explain shortly what it is. http://www.jlpt.jp/e/[*JLPT*] is the abbreviation for Japanese Language Proficiency Test. It is an examination to, surprise surprise, measure your Japanese language proficiency and grants you a nice, official piece of paper stating your level when succeeded.
The examination is done twice per year and you can apply for one of the 5 available levels, starting on the bottom with N5 (the easiest) and ending with N1 (the toughest).
Last week, I took the N4 exam.
The content of my language course exceeds the border of the N5 level by dozens of miles, so I was ambitious to apply for the next level.
The only thing that is not really covered good by the course are Kanji, which were crucial for the vocabulary part of the exam.
For N4, you should know around 285 characters plus a ton of words you can spell with them.
Being to exhausted from daily school life, I only studied 120 Kanji (enough for N5).
Hence, the exam went as I had expected: I had enough knowledge for the grammar part, listening went rather easy, but I simply don't know enough Kanjis for the vocabulary part.
Since that part went rather bad, I doubt I will pass the exam, but I will get my official result at the end of January.
I still have the examination moment in July, for which I will have more time to prepare properly, but being ambitious as always, I will try to achieve the N3 level!

If people start to think all of sudden I have had no life outside of my language studies, don't worry!
On Friday nights I visited the local izakayas in my ward with Sašo, Ole and other friends I made during my volounteer classes at Musashi Kosugi station and got in touch with some local folks over there.
It's a great way to practise some casualy spoken Japanese.
I also went to the http://fes16.moshimoshi-nippon.jp/en/[*Moshi Moshi Nippon Festival 2016*].
It's a festival promoting Japan's teen and pop culture.
A nice thing about the festival is that it was free for gaikokujin (外国人, foreigner), or for short gaijin, but you had to register to get inside the venue.
The festival was held in Tokyo Taiikakun, at the border of Shinjuku and Shibuya.
Outside the building, there was an free-entry zone with food stands and an outdoor stage.
Drinks were very cheap when compared to Belgian festivals.
Inside, you had various booths and 2 stages with various performances.
Despite having great names in the line up, the number of people attending the event was rather small.
The event site itself was also smaller than I had expected and the booths were mostly focused on the female products like make-up and girl-magazines.
There was a Resident Evil booth though where you could play a demo of the soon releasing new game with Playstation VR, but I couldn't fetch a ticket unfortunately.
I wouldn't spend my whole weekend there, but I certainly had a lot of fun for one full afternoon.
I expected an overcrowded site, but this wasn't absolutely the case.

[[img-moshimoshi]]
.Overview of Moshi Moshi Nippon Festival
image::https://lh3.googleusercontent.com/Bs7K6Y_aojyDsm90g9gTCmnGFOZbvioqwhIv75jaU4OSHbXQhk6kfw8NOCr3qiEYmENoM_wq9P3AY0l5NFmh3mLkN_OXOUEn2QbN3j1fP4NNE0tK0Dq6jwRJvhljPjXWI_qQVvVFmsIPlHx3levHmLQ0uh09IgT7w2QsNSeJoM5gmCVgZe-bdEuSYq9LrrlWcDmKfgQzzXEuR4vAnN8kY2aeoSyMz9q6Tgeh_rF-vsc_cx_w3_nn0VF-BSflxeDKaH3sN5A-n7E7Tbhykx8tU6PaMqAXPEXPKKAczNudPOuU3ml10bEQwsbEtFugaNG8hO-itnz4YIiRy10SrtiYtlmVeSOF2mqKNeqvDSM-Eb5E6HP6qblsYAfaGEpSQWGIO6kE6M9tPyc7i54UBvaSL43GaCQuiib876TFvj2eoYYuyp5lBKoDrHifsI7Wt2QaH6ESbT6pCTnDHzgaMgGVJ9Gnb4V7spZzYxwnRScOTHOfionta3J0OH4hTmOimJor_zeZV1uNCaM_zKEUxpMW6xj_zPrHkmCxA5iovYcxbSm4NIRMP49rgSQ_-r0mYg5TRxvcpW1_ecdtx9EWs3XTp_Fw8nMY408glxMrgxfnwl6tRX6a=w1267-h950-no[]

What I really looked forward to was the performance of *BAND-MAID*.
The timetable seemed to have a 10-minute block for the band, but the gig almost took 25 minutes.
I only know the band for a short period, but really fell in love with some of their songs.
Their performance blew me away.
I was certainly satisfied and glad I had seen them performing live.
Their genre ranges from hard rock to heavy metal but some elements make the band stand out.
First of all, all the band members are girls, which I have rarely encountered until now.
But what draws the most attention are their maid dresses.
People who are familiar with maid café's will recognise where the inspiration came from.
Two band members happen to be former maids in one of the countless maid café's in Akihabara.
During the gig, one of the two vocalists did the well known 'moe moe kyun' scene with us.
I found a video starting from the 'moe moe kyun' moment and the second part of their performance.
Due to the volume, the recording doesn't sound great, but it gives you a good idea of how the band looks like.

video::pbCfuKlAtkk[youtube,width=560,height=315,lang=jp]

[[img-bandmaid]]
.The best picture I could take of the BAND-MAID performance
image::https://lh3.googleusercontent.com/fml9ukj4jSZKwYEiSXF0VQqZ6CRaFdfLNJy3cVVW5kT4SL7wbk2rrQZQ6ENNxf8q5_Hv5MVHvlGbP-efiZDAjHItMMUMa0Btz9kOluQwXCl83BOrGLg9LFwum_Tz4eSENstBvNHqN_l1z1M6rTGMAiii1a1l3EpDGLX8md86ndKKaquu8KqLgsz3T162n1TsvcFunndow038AtCyBQZnzcwzkyPbK3QQRkGJ5hPAIWBY_Qjr3JS3wuEoH4cv8JzIBsZlChY5o6mSkhlKcqkg-OUbb0YeNbZI6juAdD8rLsdf7GZbV5e2QUPVY-IU_0s5AbuDWmCAyCjll8lHbQH03JnBuqLYiLpcn3Da_tOrSzfq1BsaZq24QDKu8zgtzOwe49DUWQlUmrV_hDGqjzfLpDqMYo9-fjqx_IjtQ6SdCwSwAZ5B3NyuZfYaPo32H8kTqVovUlrfX1QEv9AHx7_HKRKDxB8zrzxSDLTFymOz2zL2HbhofKlEjWTbO2oyVopWrOxmMIBrdpx5VBPG7vhcXGxJkcIwMWpaN4e4jEWUHoUfqup4td2dPY_FH7hEpQbEjYLm6d4I_S9ZJtyMDdEFczWQHI52eFQF9Knp4uhqE9wAB50BYwfU=w1267-h950-no[]

Outside the venue, I saw a performance of *Niji no Conquistador*, an idol group with quite young girls. I haven't checked their actual ages, but I had the impression they were around 14 to 16.
Their fanclub was clearly present in the crowd, throwing in all their screams, jumps, even one guy stood (litterly standing on his feet straight up) on top of another guy cheering for the idols.
Really funny and impressive to see how these fanatic fans give the fullest of themselves during the performance.
I ended the festival with the performance of *Silent Siren*, another all-female band in a more pop rock style of music.
It was also a really amazing performance!
In front of me there was another genki fanatic cheerer who almost broke the camera of his neighbour when he was throwing his fist in the air and jumping around.

During November, I also had some cultural events at/with school.
On an afternoon, there was a calligraphy session.
I tried at least 20 times to draw the Kanji for heart (心, kokoro), but it didn't turn out the way I wanted to.
I blame the brush!
It was way more difficult then I thought to draw the strokes the way they should be.
It demands a lot of attention and patience, which I didn't have that day for unknown reasons.

[[img-z]]
.My final calligraphy drawing
image::https://lh3.googleusercontent.com/Aivbfd0af-60lPmkZOHATAzQIW9iFvo_tSuvlUpCsd6CyAajfzRjUiCTD6IfIUBvNHtjGTifB7QRw4cuDwJP2Zbk95ORgrncpwrIaglIqFjaz_sIAfJ_CO9tejW-H9V8_cyA0fO__Y6eSjY-BiT9bEwq-FczWTEDWHBt0Lm1TBh6oHahX_MhqUYL3thReFm7GgIMDq8dxtLhMBDZhA-57faRnRaw5bTmX6vBquO_i4e-boLrBYZ2tl7oc0m6iabacWSLQKLCh5US52KaZLdWIoZICLy0RUbOCXXRzT7Jv6zIgCK-dIiafopgut83hV46l4DMNcDtucUmWaWy03Fagm89LeQo_xHh_CbsvHyTXfi0nfAKqR81vK25BLUG4ck_VbIJLlOxuBdRGoVZCx5zD99UlhDbTItKWkh_vn4JUpfOyTxsgY5X4JMLsjOD8Zpss1xQnXjMOwc4lkNcqnPcwcdj9-RPF1od_1yWSLvAlEjdVs4Psm0btfGC2u17u9jQ5NPmKKLb8sn7VMJgo1DkMUJx9owdiYwQXF8coYEaPsFPhYTANZO_2hzEJqEJy5PsYb3Xz-sl4uoTcP8bNE75rjQKW4H5Qg6hbBGP4JyqOl32Y9oDU_p_=w713-h950-no[]

In the same week, we also had a school trip to the http://tatemonoen.jp/english/[*Edo-Tokyo Open Air Architectural Museum*].
Belgian folks can compare this museum to Bokrijk.
The museum consists of old buildings, like houses, shops, farms etc. from the Edo period.
There was even an old style onsen.
The visit was finished by a traditional Japanese tea ceremony (茶道, saado).
The day before the ceremony, we learned the proper etiquette during the ceremony.
Being scared to forget some of the steps of the ceremony, I was really nervous, since I didn't want to ruin the ceremony by making any mistake.
Next to this, the blood circulation in my legs decided to give up after sitting quite a long time on my knees, which became really painful.
But in the end, it was a nice experience.
To finally end this blog, I share with you the small number of pictures I have from the Museum and the tea ceremony.

[[img-daibutsu]]
.After the tea ceremony we had the oportunity to pose with the equipment
image::https://lh3.googleusercontent.com/5qoCd4NbzXbTJNejU18tuK_YSaqK4CcLfkHv1MpKXvisCLYwjB1zOnnXSM5osW9YrmDg9vr1xxzMi7XCnDfWWpJ8K29uWjdpp7sWYMeq0_NupqyIsx-xVO79N2OyoaWwaqbas1nz2dCkpxHe3G949fnP2vTnMbuKF3OyAtrk5J4rhzyyATfgx-4XSEQRoA4_yh1Kp6wMZ9LDbPqL2gpevPLfhktlZ-cA9rfVAo88lBn6OxP9b8iaUC4aRhJkYdk--9CpwLEbtpPBU8FWa8uUH32HYUsvtx9g1ZOPpwUOLeGozI8ZC1F3RPF-ploDqYAS7dgTMcFTG7JmMp-DJrPbxB3obaydACF2NbUKDnqMFxKTwDPaw4t59L1--DKnmEX5GjfY40ME61WhKUbDhBckLowUOSMnSkP1Otom2tNku1vMwKSc4-z1ESl9tuvE7PCKiz_4YpJ2tajiIb8tHjE4HIY7uBP4yv-xjzc-O_f7FwAVC_iKaHw4qLa7jZqO2fBfA6zX-f-4SX54BZ6kagd6QTUUQXmjBymNKbpUwkbUSzju6r0-QOAZKH-es8B2h2HTXjCOkqtIUKhgFaZ4zro7TIR2Qv5tC4owNX-RxPb8X7kwbMz1BACTDvscOtzzYD0TPvrE6K7NsOX4CTkKwKfLyC5t6HtergGD8r7enhoUWw=w713-h950-no[]

[[img-u]]
.Close-up of the equipment
image::https://lh3.googleusercontent.com/66Jzg36A6u5MsDwNog9GIvNPRLmBzLm89gHhBpX4cUDYMTo7R7bx0g4SMvQKkwt-69gF80bSMYr-IoSIbKPmC-k9u5Ul3Y6kaYb-CRfddI7afT1DruUlE3pKHIF925xpCyH7Qc1KvYwGs3tIO4xhpA3nt8e8PKuykD8-leBUGEcUSnekWga3upu-twVYdZECcrD1yZ7hMSgd-tjpuY5nPbELWdGZW880koRfFoJjwedPx63GXBe0WE6UNsIBx1fxsLrZ2ibirfxVoL74ROjZQdbQfXZbD035sFNvEo1EZ7UXUf1I8UztbkvBZiLdUG5XVJhyLhprKFZfPZ-2saeh5YXS4-ri8ol007LaCcdvsJWIyxFXk4W2DvimpjQh2t_Es4GPvngksDItYhEBpx7QaCjJo2cMPGMyzWt_u9FQ1PYoSEfK5oLbbvnSMzMQx41ar-s8Bm3AO9RXLb7IENxitC_UZASUzBZideDp6AmiZ_IvAvv1lSYIG7mj5U9_Ouw94_ei50Vqjyi1LVzCj5aO8lc8yw8savWr7VkFdlsE961MHo6PGjM223vUeCRiI7Z5EV-iQmhJknTdJ4WXWPb2NjXyoi1zZMpPWS5tGz6ylbCpDvqvskorWO0cAOlAS2LP9csJeH7WJrHKTXR99eWdDSElQ1UX0AMo1sAiflukkw=w1267-h950-no[]

[[img-y]]
.Inside the onsen
image::https://lh3.googleusercontent.com/fFr9oXntDswR2JX4gM2l3rXdIX-8W6DyZSNoeST_35Hi_8Egj3caLy6nAB1Siln2rmbST8apB35UqRsJpYacXdi__5v98OI7N36O0ZNM5wf5odbaprPwP7TWRIGt6tfjZ0_Gar6ydN-K53cCLPSabtyUdbjx7FtAMd-rj17s35BiLXfvJkCoHZEH6tZzDQwHimRzBNAh7-7pC35imPyMGQIUlKF-JIgDapApm5Z9E3fFLcFU4mHuFLXQFTcEuYc9lwPx0ehiIwF_a4xcFS94fM67g8UgXhEsqPIGwGIGI85IL4Mdk-M0XqtO8lxxsQOU_FqwnwtlEYmoXzdYIuqxjHbuUtVP75-9LecTfbZityL2EP24IbIBRMFo0gnMMvD-zc09u2NtHbhPRTdBpqg32pfsQMBLmL9uwvxa0IA21reUBJCbv3lGFJ2skhgzplDVwd0xwcQOcbeWBKhV2-iINP_l5aLKsn4qydB3pU6rbZZyehFEgndE80K5NyREwZVgp5JFaaUFkSGyiAFS8vM_a-TM96zBZ5CGwu5J6_PIG26l6U5pDzono_an44W_PKCOqUsxsijKNHTOL2IkXQOcO_MLoYq6QZAofIKKN273CSeSCwq5=w1267-h950-no[]

[[img-x]]
.A small mausoleum
image::https://lh3.googleusercontent.com/Fuy7PI-zLcqyd260uxaRl10nv76P1HdgnHvBlqF6gnZDZuNTDWwt3_WwNpJs-lubgBNi8G_u6XqddBUglUGCi6G0niBeqpUAA3qi2BNyPZo-cLUhP2gA7lvcjfhQLwYyP8S-4a5Hchr8oPHBzJBP3EGaLiKE5zJknK6zGPqdf-eEMq0qIsqEi_f0VXmC8J5RwGXmqSgNHXF2zrQhkMOENbGAYcLiPcfE5WkPNHh-jhCRpggrBtopWslk_ERn_6cAsri4vhtUU9rm6jx_xmOceEQCz-9rox-P5tGi0cII6UprqOVvrd8KcY3uCmk-bDC17BP8lWSiiF0sqsO5iPcQdS34z4bZEiYiDcDumxH2-0dts6_tXXVoRvREXBcjlDughq4XLktFvEFDd-yC2YLcHvCS7Z8vesUbi_hV0-ulTP8ljd8c5-1ELYNnSy_BHgNBtPz4u036Ptei0GVBmtX7oo2l5UMEGQ3rY0IkVSRAa81tZeEYTPiCGonALulEpHpTcY2wQMLeX74E9PruwqDknjtizCVbtazOYfaWZ1sZ-TFgyK0zC4UAftOoCh9zyvq7Qd_0cbMhOheD6IbsIFJ3kMQzrfEs-H830ik8_XOQWbbuAZ0x=w1267-h950-no[]



