= Kamakura 

Let's tell a bit about the places I have visited! I have walked through several parks in  Tokyo, made a stop at the Pokémon Center in Ikebukoro and wandered around in Akihabara drooling on all the anime merchandise I saw over there! That's only the tip of the iceberg of what I have done, but I still need to explore a lot of Tokyo. I guess I will get the opportunity to do this during the Christmas break. Last month I even left Tokyo to visit the beatiful city Kamakura (鎌倉) with 3 other Vulcanus trainees. The city is only 50 kilometers south Tokyo and has a long history, which makes it an attractive spot for tourists.
What can you expect to find in Kamakura? Well, it's very simply: religious spots, tons and tons of them. The city is surrounded by Shinto shrines (神社：じんじゃ; jinja) and Buddhist temples (お寺：おてら; otera). Some of them were built centuries ago and still remain. 

We made a nice roundtrip around the city and witnessed a rather green village without skyscapers, which really contrasts with the Tokyo Metropolitan Area. I felt a bit relieved actually to be out of the big city for a bit. Since it is way more interesting to see for yourself where I have been, I decided to make this post more interactive by adding a map of my roundtrip. We had a nice walk of around 10km, starting from Kamakura station and ending at Kita-Kamakura station. Of course, I also took some pictures. I'm not going to waste a lot of words in this post and let the map and pictures speak for themselves: https://goo.gl/photos/G2qetVywN4awRXzq5[*ALBUM*]

[[map,map]]
++++
<style>
    .google-maps {
        position: relative;
        padding-bottom: 75%; // This is the aspect ratio
        height: 0;
        overflow: hidden;
    }
    .google-maps iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100% !important;
        height: 100% !important;
    }
</style>
 
<div class="google-maps">
<iframe src="https://www.google.com/maps/d/embed?mid=1ich19Hjatxr5G3xoG0cAjqbUIn0" width="640" height="480" frameborder="0" style="border:0"></iframe>
</div>
++++

Our first stop was the village's most famous attraction: the great Buddha Statue, a.k.a Daibutsu (大仏, Big Buddha). It's a 13,35 meters high sitting Buddha made out of bronze and was built in the 13th century! It's set in the middle of a Buddhist temple and it is even possible to enter the insides of the statues.

[[img-daibutsu]]
.Big Boy Buddha
image::https://lh3.googleusercontent.com/kiPrNwTGiaKTkbAHdztH0AEXhwZiqpIxorv6VOqvXWWHT8zMklea80Wgqoyze3jDNjwepQ6YOu5RoywapiOqzdNYa9f7Psxi-oPcNa4AfWzWB_Xv2X2ITTIMS0OCN_JRUOB3B6lWUyiQC1r5vJljkoab8eK9zbqBJhT8PAo9w0_DYYR46_pBqhYxRUTrgC8egrliYrN8Eiv70iYeisEfWhSEUVFZJhPhtKXpf47NaxMMl4ictqEZ7y-eXXgTmXGAv7QCCCa-CltIeOlmSFAdfsV3mbGHcyXFfF-j9MNEmXNalEbnywS0iIldH-864n6owcbR6Zj-a8-HIUnM2nudvf2XB4hdI-6KIbOZa_FvYBb83cnqJIy0j7B4VbqH1Q2aD017oxqACiXiysjWjzwm4MdM2tVfrEXZBSPYlqAtnZPY0sawMscZQDe11DMHYn13CiPOENnr-LOSo1aOtOoqEz37GFXECN0hSFFTsC4u_t5f2ZirHwM9bEzOcvyuwbV1YfMA3lkQdmrMVi2tmGZBASMoX6XB0JFjb342tEyWHD5P-DE6r3rt8X2Wb3of8fbO55tVPqDSUrg9Cq_7dKVpiIHRwfxBMCvpgJJtk3zGafHjosui=w620-h930-no[Daibutsu]

[[img-innerbuddha]]
.Inside the Daibutsu
image::https://lh3.googleusercontent.com/TK6_SUZyHmUtfnNsuFizeV5shVrmYxbiUI-GRagpnX_NwV5LxzsVS9XfV4hASfARMbatw38b9KWtFrtopF9VIWD4t9bM3THP6f6gq2_3RX8o7OW3R_p1yUux9a5nYREE1abQWKk7rSVeuNzrW6CpnRhQ7XvT_vsY1HV_vFaVmjY66B4IzC3H-xTlr1a39hadGJaGLljStiCXbkgDa2KO-HSPBCNZ5i45FpU6HmduW0njf8IK5tilkzndUzWrn6gHY3XxMoqQUHzdGoehPgloweW46qZGnWh1uGVr12hS71uIuprB-z_AzwP-FPhtWN0TivNPWmcKp92giyPtGqnNiMh6ffoa3E5XLhMSdD8McJTOL_RWPamCGKMKgmYQM0IIFH_o_Wy8RuFEUTeFUrmZ06B41uLwHjSDZnDrUFbQvB0s1lbo8ImTAg3n5mKEK5NuTJjFHlGhb17YbcEwlM_rMBdRFmwlUyLqO9o5HYne4-bN9gtS0rLugaMZv_jEm1NeZF5atjATk74g-htVehiICsE37kJ6j4gk3en9mcPb0ZZtQ_rkZZIriMYn76AXVxPptBt5qu2EF7k59KIQRSJZR_JkrJ_0gZcGHdBtMXi0bnkFWtN_=w698-h930-no[Inside the Daibutsu]

Our second stop was Hase-dera, another Buddhist Temple, built on the side of a steep hill. It is a big temple with a lot of beautiful things that turn you speechless! You can climb a lot of stairs, which grants you a nice overview over the city. You can see eagles circling around Kamakura and see the nearby beach.

[[img-hase-dare]]
.One of the amazing sightings at Hase-dare
image::https://lh3.googleusercontent.com/J6spejxUoL7QdPDIzF7fAYWmmMZavUA_4Emd100COSP8QhvPZnwAsmOPQswA_DWtJCkaK4T8crqvlMOVzborPHa8WkJAIhPyqQpNYyFMHQTyJJ7FzUUDJ1W3BFHpgDTEoTslo1VtiZoGitUkg_AXabQQW8SwXe0weZJ-eEdT0zUm3IuVUwUv3XjegoN-85jP3QFSNiBhMPyKQnDWRg6gGa4DsA1nPVKhec8jQgxa2lOhtLMm4Qp8sRx0UwY1u4paGrIkrTL4DYatrajbFohYIprj77OrxoeveebzrMboWOUZ04v3drk83icxvAuz-_a6iBmaru6fJ71pVAZ_U7-jU4ElgqWzLzjRHfk625MF0IDocVMw6gklUN0KyD97HlES_xYlKFRZarVjGMiajCq2Nih6dqMhSdz6aqZrihgykS6hNMREal6KHEek5rTaMUPzqxmpH68L-CPW93lYxg9x70ABW75C-_ndWjqEN0GNvG_qb2H0S2rkcktZI3ylcXuh0EW1TzHnmGJSdvsVIZDO-MRo2xJuaG2Qm7zEQ2SLyeujppxaYy3x0Lk-X1GtqIwk1GVxCUYyP0IUK-xvmhGtDBeZqKii0y08XL-l0YTkUjlMCssP=w1240-h930-no[hase-dare]

[[hase-dare-view]]
.View from up the Hase-dare
image::https://lh3.googleusercontent.com/v8CnGwn93Cwf4_c6pQpOPLCp9e7n2xlM2iW_wQZSHQvWgVI8TspvTEoTXnzmplYAF9okGDRAPRiKbuj0Cr-W-sTyJ_PgjKaPYg1nIX2fBHtbxzTA7qektFo-_2BOnOfRccr4APrUvQIOPV7QayaSAUNQW7MRy5K2s9GnjL3R-8qIvhQy-fmJDV3709UWG_a1Ot9h3ZDikgcnf79Qv4mkuNQ8d9eQtpH1libhjPwI3SfZMgqDtff73ouuBiroWizfTX901aI1JKT11djyWb7WNM4cnl6Z9L7FBzQzuMngzyBBkpIZbKxghB4wrJdQqRgNxlXv8WP1_azXUbrKmRZwdwMS9Zb2_7V8Q9QhUAgzfCte63QbsLN2UlFeWbXKYCW7KTgET550VgfuFbgvccClEe_aqPh6yIYOqyOU0DzYsQUDoOvlieLAlT-bT021QxWzwwwl_iIAipGkZyD6B6NnIGJq4G7yNRfHRIQ3GA1aXQvL7Axyd27H1QHjPtFVKT91OpsTnySllY4EFk9tSnkZKlOk1Qz9Fx0Vvp1BEWhjDOHuSEJYD48fwZTwab7hz38joRvoGCirGQpItiNKu46oVjwD0bwCtriB4JYaZCzdNThkyYYD=w1240-h930-no[]

Did I just say beach? Yes, there is one! That was our third stop: walking on the beach and touching Japanese sea water for the first time in forever! (yes, this was an intended cross reference to a Disney movie)

[[beach]]
.My first Japanese beach
image::https://lh3.googleusercontent.com/0Psx8Ln8D7ro6SlqA7kLQXQ_CNNLo57Sjbr-e4-ZES44982G1td5_v8X85NlJYT8VeVRQKIQ_95jwahwsYSMQZTPfow72IEkzUigIsdnSbNESKNVJrLAivOlfaiRP0kTj6Mia86x5Giq9Rz4xZgzdnMNfIKo3H7AIlMphdQ_SFUqumEWHWuL_Ya3F_sr8JRYLM_oMdPfN_XpyQajc02OkfR8hxqZGCA3PKJI3EcOk9qgWcDXtQnNAXPnMbLq9ODp3mRwnFa07Yo-dsyqlR3UjKaA_9dGZD7581vfB0piLpLpwqv7kcszaGFuhoI8FwSCKgLGxZGNG0CzkA1Q_mHrJ9poJf7a0s9XLubn9EWqhhivl9ElCz5RsdKGJOoGySffULGP0KtQLMYXBqjHHcXsAFZkBRLLhRi7Z-Hmrw9rIBe6lTTP6HYYQL33Kvem3FoouTqPm-_LU9o3LwEBa-Gw409mZgfZhRI08gCQumN8hB4BeBGBcRUlJ1aR_xYH8iSKitSuyay5qD38Gf_cKIM8zmn52wX0cH2DA-R8UvQdjYJJWacYZMZ_yZGIgO0VFYV_eLldB5G5X6nU0bZRag4757L84ZBlGjHglp1U8NESnxzF_fnX=w1240-h930-no[]

After that we went for the Gyonyama Hiking Trail over one of the mountains surrounding Kamakura. There was a nice lookout point on the route, giving you a nice view of the village from the west side. The trail brought us to the biggest Shinto shrine of Kamakura: Tsurugaoka Hachiman-gū, where I was pleased to witness a Shinto wedding ceremony!

[[img-kekkonshiki]]
.The wedding ceremony in the Lower Worship Hall of Tsurugaoka Hachiman-gū
image::https://lh3.googleusercontent.com/g4agqHTMVyKoCWaKn2whfy4Cx2YeQJq7NhHyGva1Q_G1aeYwzfhul9KLEABBzguTPPdDmL0O9IP8XomEuGfq9lUBenr8V8EbQ7m6WyDw7gR6JV6UIN7__BEQIJVMsHvALxOcE4Qu9IA5SLTM_YYjcSF52PJqlU18dzCmFulcFXImjnVATV8NTqvnAgty-UOFee_CTTaAI4xupx1-cLDMjpUKnLoLhb-dN7zsHsiVmp_w1h_PjGqz8MKNcG-po6tLQOwo8EqnBkpOWINnnM0N9hIaIZJRotaABTF9AIcfbjW1Jku9Zyk2Nw0majsPsC-gMzvD6MuthpPsLRhe5a_g-WawsXRPQgE66v2168RK740JfELcRR7ydikvME_8-pS0OckzTGvKehqSRYoV68DBGTCAtvSjGkSU03hfqqOcENDVS1A41-WC28hsxeMn0rz6oD-bZH2gNe5BovcNkCMdj3-Ng61dz8Wdm-A4pGng6IZJPx9Iolh80v4tdkvJMqHHVZ3o4Dc5jEvJnQ0exw8d2gZaaKcqaKUKiG9bXPiTp39690irT1hOOF7Dc27Jh8iwPhrSpgXUc-3HU4D78N9YAi7yJSK7IjFhzBGHkayC7aGivpFD=w1240-h930-no[Kekkonshiki]

After the wedding, our journey continued through the main street for some food and then we walked al the way to Kita-Kamakura station to visit the Engaku-ji, a Buddhist Temple just besides the station. This was our final stop for this tiring but oh so satisfying trip.
I can only say I have enjoyed the day from beginning 'til the end and can only recommend people to visit the town for themselves and take the time to actually walk around! Most of the sites are close to train stations, but you will enjoy the green environment more by walking from one spot to another in my opinion. Be sure to check the remaining pictures in my https://goo.gl/photos/G2qetVywN4awRXzq5[*album*]!