= Winter Vacation, Part 1: 北海道

I know, I know... It's been a while. My sincere apologies for being silent such a long time. As a matter of fact, I had lost my motivation to keep this blog alive, but my time in Japan is almost over, so let's end it in beauty! There is still so much I could tell you all, so let's try to get started again!

It's my first blog post in 2017, so that means I still owe you all a Happy New Year, so... Happy New Year everyone! *_<insert party horn sound>_* Now that the formalities are over, let's get back to business and pick up where we ended: December 2016. It was, as usual, quite a busy month. The language course at the Naganuma School was about to end. As part of finalising the course, we had to give a small presentation, in Japanese of course, about our studies and the coming internship. The school activities ended with a tears shedding graduation ceremony, followed by an even more emotional reception. The Vulcanus students spread their wings and settled across Japan to work in the research departments of famous Japanese multinationals.

But before we jumped into work, it was time to enjoy a 3-week break. As to say, it was the longest break I will have had in Japan. Three whole weeks of pure freedom, so what did I do during that time? As you all might have thought, I enjoyed it by watching anime, reading manga, staying inside, playing videgames and avoiding sunlight as much as possible... But since I'm used to do that in Belgium, I thought there could be some change for once. What I did instead was traveling to the most northern and southern part of Japan: Hokkaidou (北海道) and Okinawa (沖縄)! 

Since it's been so long since I ever wrote a blog post here, I forgot a lot of the details, but I'll try somehow to make it an interesting story. This post will be about my time in Hokkaidou with Sašo and Ole.

== Day 1: Sapporo
In short, the first impression I had when arriving in New Chitose airport could be transcribed as follows: "Oh look, there's some snow. That's cool... And look over there, there's more snow... *_<dramatic pause>_* ... HOLY SHIIIT, THERE'S A FUCKTON OF SNOW EVERYWHERE!!!". 
It had been since my ski trip to Austria back in elementary school that I had seen that much snow at once. Everything was white: rooftops, nature, sidewalks, roads... Everything, everywhere was covered by a white blanket.
We took the train to Sapporo and stayed in an AirBNB near Hokkaidou University for 4 days. The first day we visited Sapporo itself.
The roads in Sapporo were covered in ice, yet traffic seemed not to obstructed. What I did remark was that the roads in Sapporo were much wider than the roads I was used to in Tokyo and Kawasaki. 
The city itself sure shows a lot of American influences! Logical though, since Sapporo was built with the help of the American government back in the 19th century! Some historical sites really have that "Wild West" atmosphere, such as the Sapporo Clocktower and the Red Government Building.
Besides the historical sites, we also visited the Sapporo TV Tower (imagine the little brother of Tokyo Tower) and drank some Glühwhein at the German Christmas market over there. ('t was the season to be jolly after all...)
After going for one of Hokkaidou's famous dishes (soup curry, スープカレー) in a place called Samurai (I highly recommend it!), we went out of the city and climbed up Mount Moiwa (藻岩山) by cable lift and stayed there for sunset in order to see Sapporo lighting.
To end the day, we went back to Odori Park, in front of the Sapporo TV Tower, and enjoyed the illuminations over there. For me it was a first time visiting illuminations in Japan and I must say I was impressed. Winter Wonderland with thousands of lights in several colors reflecting against the snowy background really gives a soothing feeling.

.The Red Government Building
image::https://lh3.googleusercontent.com/pQgBem_oRL6YjRIijB4uCsB8vlpMd3lBKrDEZhO2-NXBh-MsDkbZtYzJQc7QDidwnCqKNNCzoMbRpckXAir1oBuSoDJ64TCU219QNVA8UpFnk3356A3GF6gkZdB2fDxFfWTEGvswAsGPJG1JPUeu8YyGTzK1tVTtstKTSIPIRpWnmsSFuTukoGDurVESvLiVBcI8UAnZJWdh3qJBXiQXzuVHogFzm7XG9Pgq2YMujElBMXDhF1mCH3cVRDShbXkLtwqKAvQ6oYfaf9dx2ewLCeI3yTVAaHHz7jujMNWihtsWw4ptlyH5jN2zPDb33Sk5-qkDh8wJocppQ93fRWez9n6pC5yoonnXQup-ij_wFGK0x3a37BQenSEZ3rBj4TAkIny42cviL0SmbBAIRNFdq_wTd9oyvxTEwerWu5O41Y0VTxTfuZVUNWO-idFSZC0Q-rONiNu949zbyPQtNzjkqgedyU4DDW7q3zdS-fSSDTZrHrF9IwX1rjUV_QiqW-Z0luRwoeu0R6huKTRGZxACuvbTwf_pg4oS5_AwYCm8FFcL4E3CTJpLXS4K9NCOqE7rHR46IR790uqq3zT6HsHUdxs2_algeSF45-PMNpHuP9xxbZMfZbuy5GRt0k7OZs_31xeCBD5w-gLQ9y5NAgHQD-G7wNvuLjblERbZLXGegA=w1267-h950-no[]

.For whom the bell tolls? Sapporo of course!
image::https://lh3.googleusercontent.com/2PP5bedaJJn09dsGZifjEtu7_z-PnFyN-9Y6DL3sN4J7UPPzRWE-Sw2lUs6GFOBh5z9HLS-KURpVOU1_OWnwvzUPaokM9m4LE62jt3MtViJqMsvjrsJyEQuWdhrjp5QSNyl6G0EhwLku1vPRNpYE3JFbtKgMSIbXk6R7fi0oiPBsPhWrGZOgfBfj6RluqpQU-Jx9_6NWDq7I_AIEg_zvDuLcW8i1_AfzxG5K-97esSK-4dYO-h1Vi7Wru3-Ff4AJwkd9bc9jAPmEly3jU4b81JhTdL3MhIUL3ynqL_ElT7SIMq0TLJrWXFFn3s1jhXX3E2r2FH3smLl5-PD2wfLoMRxS0KZ-Ae-_QuxLJgTWGMOU9NdUBUykcjBXQnI4lFHaExE_AbU7T8osF4gESxUZgmttpJBEU89uMJunSKFWKfNNAHaAxS66vV4Ys4qv7zjpSILFLk9CoT7sRI7B4rWMqguWRAT5HKIYCe7dVcFdChhgylWA5UYK4ZktnR2TtopCqBtyziOmSxMYPZRX1N-lwoIa-he-EIOd2uE4y7MBTnDQpeGY98AQeih8LEnoVzc6TuetYuA5LxRhBV6Qjw5SBJ2TxAUCXoz0K18gWb90fOII0XUVwAdWcdSh2lTeOQg6NI2Vb19Nod8xmnBXtXKhh9bDAi3OKbjvons3JXI45Q=w1267-h950-no[]

.Sapporo's own Tokyo Tower
image::https://lh3.googleusercontent.com/GZe0Rff_WcImbU8du0i82IvEnlEWR-oD8aBlDUuvmbIuix08bLNPJMY71gbtJYNf4MP3_lbyu5XUn_3pHCxkeo54U2hoG7-vfn6jUMxXCmfsxZA61-9-oYQ18r2O_qBygEgQh9ZG-ECT0emErTg5DF-YeVHEn4PWhCNY56QdcUnaqZku8FQPd9_R24KqJZf5TUeogqql7ojspj6_LoYox0OsflQIwjKy1J29Kdpt8fNMZfKhfuHg-XvWfYIwv_B5IOObPLcvCpd8oorglGN22cQyA2UNuFHwO3QDhaY-k0BCLbfoY6ulkTcJ3WMzYq2JOJIIjk5VQq7HkSOwVGXon_s3fEb5kat0l-mVPcGD9mMuTBUIsN1eybSTe0Wr6pz1bCN_io-u4EAV6hbwPurbUhHrZvqRjnl-SaDONPXDmzg_OMpXE5Rd48magU02lAcu1TsyLd15-3gsSkG-bl7dnRIbZEMG8dpV-UE4YVg9Jg3rO3XbHisMpR4BQLujyttmDbjP_jeb7KJbqcVBoHL5mOWV2nwknaTUCVcd1YaZ_hKLnJuNUGY0LTANj0GJLawcDT4Vc5gelr8t3kpCvxfVEsTgiv6bxg_P4tpsDIp7KYwPKUG3D1_0yu8yDOtbbmZ9AHNZhk6JzJfY54EQl4RdU76mS9HJGMBAHlzLWMfAZA=w713-h950-no[]

.OOOOOOH! Shiiiiinyyyyyy
image::https://lh3.googleusercontent.com/4Paqa4OPwIxu0-Iv6ftEd0fR0LIScN4vfG-z66FV_sQXDvHy2e4yPikI5DnZiR0tQogr2w_7bkQi-rRjm6jf6VVS10iGWHCl9M4Gw9e3bJWVr0B9jiALWLdV-eb2VeIWHf14MyykTjTWQ4ksTJGG0bq0PkgdsONya1qxscDqIHBEJ_3y1eEnqTvOsv_KeeCGeRmwzVd6l1ygxOdv7NXnh7jMKz7XfMyzKyoa4jwhXz-bXSQwPUOMewdLRuMArjlF7tZAP1DYfh6qZpv3npyCFKb7HP_PrAwgkeHepw-g2tSF4GaPYs0tUJEGwkzmY3BirQRvAfTqXtI5EPPI-7uvnMlxpeplLpVVm_v-aOFJZ1S1KX3KC0tI_il9rrcPjqaaD99zqgmRjkfPKmtqcmckRxqJ-2grBA7PQSx-XPqYsuUorma9YDI7oAxQs7IfAzd-dWXsMxZpjfeSTG2OEmHURXZ1H0aKe9lzqTd-8Yechig__oyMaA5ZPSzYqG-8HUZqom6XB9P4lQNV2s5mfok9LVREYq0JidMO2H_gKRzxfL_u2zI_KmTTcX30WCnZos17WnU4sDwfd0R7a9fu_vWmVRcWhirUWa3FCa9ldINec26ZCBuxvmCCZXP06PeXPUUM_QE15fNFsb6ufy4XgNTe0xJrLhrzMqo8wDa8x44BSA=w1267-h950-no[]

== Day 2: Teine ski resort
The second day we went skiing on Mount Teine, just outside of Sapporo. We had a bright sky that day. On the mountain we had a great overview of Sapporo, and could even sea the Japanese Sea (Ishikari Bay to be more precise).
The ski tracks were very nice, we mostly took the long track which was about 4 kilometers long. Of course, being as excited as I was, I was being a speed devil from time to time, with the result I made some gracious face plants. Luckily I didn't get any injuries or fractures!

.Skiing with an ocean view
image::https://lh3.googleusercontent.com/o5G0gnrpndMy971dLIlHKgO5pfqPIo0VfE9i7m4AlLMhpg4FRMuO0UVISrIwZS7gwj_maNjoDzyXrvsV7TANZOmgf2VD_MEkWmWdxkGGLZrYju6Za7BCUGdZK3gdJna8r3KM5KErCVfDFChRjJvYkmHqFvbFlZFJZ_udH6OKhTGlFep6njpZigvM5EuiW5SEyV6oLXb2WXHH3sDVo2j4WcAXqE4T9fom6rRTScZDB9JwskNvOLZ0jwZDcb_ub3Z-gmpwH5vcG9ltaRcZ5cAMn4rbD-xvZOBwKp90i2m40TXuI-S-mVopJhME9Ao7sb2mSfao7qKJUmxh_JCu_lEp_RLyH62KqJbn0X1qYRp9Wya5K_s4uTUBXZU13uhzBeq8644084MyktyC6AJxMIh5ywU-FEwFzlV2kJF8-j3WWaZqch3b36OQnwFH9r55ZTx2ZhperYE5dNZZjAN61xyD2jxf8puE4Cu68OpZ2poUWjRlk1MES6Fh68hnONGGBkvBwP5FQ5Q0vOEexnA9KwOA9WjJzkSSoZV4l2F5K1ONjFGpE2z4BQT-SL-DiFvIZkpLTwrh6yqkzFWX8PmngqJ1Oswx2q26--Ts0WVE7HesWrQ1941W4TKMRLTOEeuE8wa6O3XC7TZKtgpf7S5mLGq1WgNL1nocWUxuwKoF9bsSUw=w1267-h950-no[]

== Day 3: Otaru
On the third day of pass:[<strike>Christmas</strike>] the Hokkaidou trip, we visited the old harbor town Otaru, which had a rather worn out impression to be honest. The architecture over there again showed a lot of Western influences.
The village itself was not as amusing as expected, it was rather focussed on souvenirs. Most of the shops sold the same type of articles: glass work, liquor, chocolates etc.
For lunch, we ate Genghis Khan (ジンギスカン). Yup that's right: we ate the Mongolian conqueror from the 12th and 13th century! Nah, just kidding, it's a dish based on grilled mutton meat.
The most attracting site in Otaru is the canal and the lighting path over there, but we didn't stay for the nightfall to see the lantern lighting up.

.The canal in Otaru
image::https://lh3.googleusercontent.com/6aKNx_O_X8TOshxzqTxEMQ6-gBitgpFv4FN8rCSYGgd1NG9B7YmrMO7jED-2fAXbD-SSC_Re2DnZR4qfaWejW2y8si1fSgRWSeP9RBKQdQEkEOB6ESdI0P4O_6jxHq1AUq5SqSWIFiOw0l4LBbvYORfspzp-5j_OpCiuv_Elpw-owWdrCCYbiUu9OuDDdloPI9yEZ4O3KEK3D2RosORB60UMKAGgn-zV8Meicw_IeMpzdrtlljoOTT_1eezuNatWm8bUThP2_nvp1vDzAMaK2Hf4ixL6GGCNpK__pi0DkrZ89xe-t0hGYbnwqpBbhBZGCBDnz9fp0YsdJdTz3rhrJksgee_PJVtiGuV-05_7OrYE-LvVtekClVSR_qZMY83bT-IlQErA3Oyx-J0A0NrSFRLPrR2t4KkYd9yIWZncnRPl1s9b1sAnvY_CiWyX3WOPQxd2ltEUYwvbZSsnN51EGLt92x2Fn3ipnt--f8qRYbLPCYW0SYy8mwn7Cd0KqJLpFR4V0sb2hyEPo6wfeRfSpYt1acCKm67K5mI5SA6n39nC1DQC5K7fz2-zU1VlqqX9X_kS4ETviEseq4mRoyJGqnQJ3wiz1EzGcV-Cb8Yv02dT5JfSkBruOlHN427I2FFj-X2Ur0uc_Xl7AcR-zRzOOj_bjMSDkHwR2HaQLXL3iQ=w1267-h950-no[]

== Day 4: Noboribetsu Onsen
Our final day in Hokkaidou, we left the AirBNB and visited one of the most famous areas on the island: Noboribetsu! After so many cold days, it was time to go warm up a bit in the natural hot springs over there. Entering the onsen village, you'll be greated by red and blue Oni (鬼,  a kind of youkai from Japanese folklore, variously translated as demons, devils, ogres, or trolls).

.Cute little beasty, isn't it?
image::https://lh3.googleusercontent.com/1mJ7QIvv7NTnulwIG3QT6_2Z14j-FbrZjbIcV9AZ94h3_bEn5sIso2qe1xcvB1h8djmvwGkb2tan3Ywh9NBmioZquG7uAW0m6_JAby8fxjsC5_LVRU1beS9-DJbBEmwdCKa0p31_vcF225IIQMteB-y8wot91VbeKac94-se4HHbtdFhI1xQk9T-ilpv_8rKz5M_shsXYISAH_Ve6u3YDaThR-3ioFM5e0sxiZpd-A9maN_UHjuL0cl-jFu-RMvgMt0Fpg7RUvxHrDkMs_bTbfHje0a7oVzHsjjzwiKaJXJSM0Dcnp6-rQUq1knanpzIFwj9V_XBKEn5_GHgRlnwgD2cEpE1CcGc7KmXBgdafj5VfFCYBtX7GNzPxFewZZAVnoxCUt8yrbNJDQ7ekURRk-MIGfKj2t_uw3dqD_wCVkeUBSm6OYgkCV244CtF_VOhZaQxzyIOwXKpgEgBDj4KO3b-5jXvY8Kl1WVExfliC6XJ-UolhVHHxTFRIcMiaoeBIndt0n7Sz8gb4wO4KomPcBAtezMgOLIRq7ecDKt-C--UuH7juwnb1pZ-TH3A9HFkkioIE6SGwhiITGVlFN5GC3gANqQbVZB2ql29bjfelUQnM-H5nky8SBekqB-RoGYTg37pvdkJASkNQBbdqRuoWOPMJI6G4KJrgxwqJ1WIBg=w713-h950-no[]

Before checking-in at our hotel, we walked around a bit in the village. To our surprises, there is a bear park, but we didn't enter it, since we weren't that interested. 
We walked by the village's Geyser, which is sited underneath a traffic road, met The King of Hell, Enma-do, and walked to the Hell Valley (地獄谷, jigokudani): the sulfurous, volcanous main source of Noboribetsu's hot spring waters. The smell of sulfur hangs everywhere, but the view is majestic.

.Entering Hell Valley
image::https://lh3.googleusercontent.com/SERv674Eqpbz4z6M6-UXdJ5GB9VPoz0j5bDaUwXG4ld8hB2G0E3UdXzEwvqtjzJ6Xca0bJZQwPEieW7lRY8oA5TSG-2mBQRgliv7-FJGAeLlnTjBNb3SzpNpUBIn_7EbWEGFMTPN39eCOy8STCjS2icUYXOL-MlGEKi1CzZGBcOdNx8gkbz_PTgguQynexDVCsAvZSTFyONoZ8jvrMKW2G1hl-0uTwhfi8LaLbgfRg6g7HzVirJD5Fp-zX3RHxosih6bJj0JAYfe8MpVTy4gbA0hXmIB5ejsxvaNaXlaPncAkp-reby6wKEZ4fXx47_RRjAeVUX-UNkdRLit3j6Eccxk_zkUHvZpGQhpjqAmMj29YDuKWGM9HDhrGvn9aAWvjtYNmNdo2WGsWtDyEjBB6RiO77STsWIIdBHZbSwJw7PIQ22D6mKRfn-dLV7epcc7JfgjxRxS1qosunCLdqEHC2LCJdMUAFAGqRrTpSNgz6GFkPsCwURRRZ1DdW9czsKaPlbvjhxbwBvQnaYrmsojdVS2Cg_diHAGnDPJ8qPNNILQUD2rjMwzMF9z2nM1Mo3jtVldKwspC2YDDxcSdhVNANXlnyzDwRn-30JUsn_qiTgbi7nfbW3IQ572KYOszmC7YzMnhNoR1_JijnyGbGv-Yv-g02FiWNpIq-EZEzJDSw=w1267-h950-no[]

We stayed the night in a hotel with Japanese decorated rooms, which means we had to sleep in a futon on a tatami floor. We got a Yukata to walk around in the hotel and the onsen. It was very relaxing (apart from the majority of Chinese tourists during dinner who apparently don't understand the purpose of queues at the buffet and are not ashamed of making their table a dump...).
After a good night's rest and a final 6 A.M. morning dive in the onsen, we went back to New Chitose Airport and said goodbye to Japan's Winter Wonderland of the North.